#version: "3.6"
version: "2"
volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
  hdfs_workspace:
    driver: local
  

services:
  portainer:
    image: portainer/portainer
    ports:
      - 10001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data

  cloudera:
    image: cloudera/quickstart:latest
    container_name: cloudera
    privileged: true
    hostname: quickstart.cloudera
    command: /usr/bin/docker-quickstart
    ports:
#      - "8020:8020"   # HDFS 
#      - "8022:22"     # SSH
#      - "8080:8888"   # Hue
#      - "11000:11000" # Oozie
#      - "50070:50070" # HDFS Rest Namenode
#      - "50075:50075" # HDFS Rest Datanode
#      - "2181:2181"   # Zookeeper
#      - "8088:8088"   # YARN Resource Manager
#      - "19888:19888" # MapReduce Job History
#      - "50030:50030" # MapReduce Job Tracker
#      - "8983:8983"   # Solr
#      - "16000:16000" # Sqoop Metastore
#      - "8042:8042"   # YARN Node Manager
#      - "60010:60010" # HBase Master
#      - "60030:60030" # HBase Region
#      - "9090:9090"   # HBase Thrift
#      - "8080:8080"   # HBase Rest
      - "7077:7077"   # Spark Master 
    tty: true
    stdin_open: true
    networks:
      - localnet
    volumes: 
      - ./hdfs_workspace:/user/cloudera/data:rw
      - ./jupyter_notebook/shared:/home/jovyan/work

      
  jupyter:
    image: jupyter/all-spark-notebook 
    user: root
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - ./jupyter_notebook/shared:/home/jovyan/work
    networks:
      - localnet
    command: >
       bash -c "jupyter notebook --allow-root --no-browser --ip="0.0.0.0" --NotebookApp.token=''"


  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - ./jupyter_notebook/shared:/home/jovyan/work
    depends_on:
      - cloudera
    networks:
      - localnet
            
  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - ./jupyter_notebook/shared:/home/jovyan/work
      - ./zeppelin/notebook:/zeppelin/notebook
    depends_on:
      - cloudera
    networks:
      - localnet

    
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    user: root
    ports:
      - 7002:7000
      - 9043:9042
    networks:
      - localnet    
    volumes:
      - ./cassandra_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: docker.io/bitnami/cassandra:3-debian-10
    user: root
    ports:
      - 7003:7000
      - 9044:9042
    volumes:
      - ./cassandra2_data:/bitnami
    networks:
      - localnet
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M


networks:
    localnet:
        attachable: true
